### ISSUE TITLE
Link to website not working.

### ISSUE THREAD

**Issue by E-fais** [emmanuelodii/TheHunt#1]
[the-hunt.vercel.app](https://the-hunt.vercel.app/)  Page not found!

**Comment by devodii** [comment]
Oh ..
I'd try rehost with Firebase

**Comment by devodii** [comment]
We are live! 
Link: https://uusethehunt.web.app/

**Comment by E-fais** [comment]
Looking good 👍

**Comment by devodii** [comment]
Now rebuilding it with typescript..
Got some idea?

**Comment by E-fais** [comment]
Not really...  i hope we can work on some projects later . 👍
